apiVersion: v1
kind: ConfigMap
metadata:
  name: circleguard-shared-config
  namespace: circleguard-dev
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  SPRING_NEO4J_URI: bolt://neo4j:7687
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_LDAP_URLS: ldap://openldap:389
  AUTH_API_URL: http://auth-service:8180
