apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: circleguard-dev
  labels:
    app: gateway-service
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
      component: backend
  template:
    metadata:
      labels:
        app: gateway-service
        component: backend
    spec:
      containers:
        - name: gateway-service
          image: circleguard-gateway-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: circleguard-shared-config
                  key: SPRING_DATA_REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: circleguard-shared-config
                  key: SPRING_DATA_REDIS_PORT
            - name: SERVER_PORT
              value: "8087"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: circleguard-dev-secrets
                  key: JWT_SECRET
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: circleguard-dev
  labels:
    app: gateway-service
    component: backend
spec:
  type: ClusterIP
  selector:
    app: gateway-service
    component: backend
  ports:
    - name: http
      port: 8087
      targetPort: 8087
