apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: circleguard-dev
  labels:
    app: kafka
    component: middleware
spec:
  type: ClusterIP
  selector:
    app: kafka
    component: middleware
  ports:
    - name: plaintext
      port: 29092
      targetPort: 29092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: circleguard-dev
  labels:
    app: kafka
    component: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      component: middleware
  template:
    metadata:
      labels:
        app: kafka
        component: middleware
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:29092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          readinessProbe:
            tcpSocket:
              port: 29092
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: 29092
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
