apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: circleguard-dev
  labels:
    app: openldap
    component: middleware
spec:
  type: ClusterIP
  selector:
    app: openldap
    component: middleware
  ports:
    - name: ldap
      port: 389
      targetPort: 389
    - name: ldaps
      port: 636
      targetPort: 636
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: circleguard-dev
  labels:
    app: openldap
    component: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
      component: middleware
  template:
    metadata:
      labels:
        app: openldap
        component: middleware
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: CircleGuard
            - name: LDAP_DOMAIN
              value: circleguard.edu
            - name: LDAP_ADMIN_PASSWORD
              value: admin
          readinessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 389
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
