apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: circleguard-dev
  labels:
    app: redis
    component: middleware
spec:
  type: ClusterIP
  selector:
    app: redis
    component: middleware
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: circleguard-dev
  labels:
    app: redis
    component: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      component: middleware
  template:
    metadata:
      labels:
        app: redis
        component: middleware
    spec:
      containers:
        - name: redis
          image: redis:7.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
