apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: circleguard-dev
  labels:
    app: zookeeper
    component: middleware
spec:
  type: ClusterIP
  selector:
    app: zookeeper
    component: middleware
  ports:
    - name: client
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: circleguard-dev
  labels:
    app: zookeeper
    component: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      component: middleware
  template:
    metadata:
      labels:
        app: zookeeper
        component: middleware
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
