services:
  auth-service:
    image: circleguard-auth-service:dev
    container_name: circleguard-auth-service
    ports:
      - "8180:8180"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/circleguard_auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_LDAP_URLS: ldap://openldap:389
      SERVER_PORT: 8180
    depends_on:
      - postgres
      - openldap

  identity-service:
    image: circleguard-identity-service:dev
    container_name: circleguard-identity-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/circleguard_identity
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8083
    depends_on:
      - postgres

  promotion-service:
    image: circleguard-promotion-service:dev
    container_name: circleguard-promotion-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/circleguard_promotion
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_PORT: 8088
    depends_on:
      postgres:
        condition: service_started
      neo4j:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started

  notification-service:
    image: circleguard-notification-service:dev
    container_name: circleguard-notification-service
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      AUTH_API_URL: http://auth-service:8180
      SERVER_PORT: 8082
    depends_on:
      - kafka
      - auth-service

  form-service:
    image: circleguard-form-service:dev
    container_name: circleguard-form-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/circleguard_form
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SERVER_PORT: 8086
    depends_on:
      - postgres
      - kafka

  gateway-service:
    image: circleguard-gateway-service:dev
    container_name: circleguard-gateway-service
    ports:
      - "8087:8087"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SERVER_PORT: 8087
    depends_on:
      - redis
